const translations = {
    "en": {
        "nav_home": "Home",
        "nav_about": "About Me",
        "nav_portfolio": "Portfolio",
        "nav_skills": "Skills",
        "nav_experience": "Experience",
        "nav_contact": "Contact",
        
        "role": "Information Systems Student | Tech Enthusiast",
        "sidebar_role": "Information Systems Student | Tech Enthusiast",
        
        "home_greeting": "HELLO, I'M",
        "home_desc": "7th-semester Information Systems student at Universitas Darma Persada. A passionate Tech Enthusiast eager to explore various IT fields, including Web Development, Front-End, and Data Analytics. Highly adaptable and ready to thrive in the tech industry.",
        "btn_portfolio": "View Portfolio",
        "btn_cv": "Download CV",
        "what_i_do": "What I Do",
        "wd_web_desc": "Building responsive and dynamic web applications using modern technologies like Laravel, PHP, and Vanilla JavaScript.",
        "wd_data_desc": "Processing and visualizing data to support decision-making using data visualization tools.",
        "wd_org_desc": "Experienced in managing administration, time management, and collaborating effectively in a team.",
        
        "featured_projects": "Featured Projects",
        "proj1_title": "Production Monitoring System",
        "proj1_desc": "A web-based application to help monitor the production process across branches centrally.",
        "proj2_title": "Fraud Detection Dashboard",
        "proj2_desc": "An interactive data visualization dashboard to detect anomalies in company datasets.",
        "btn_all_projects": "View All Projects",
        
        "profile_title": "Profile",
        "profile_desc": "7th-semester Information Systems student at Universitas Darma Persada. I am a highly motivated Tech Enthusiast with a broad interest in the IT field, ranging from Web Development and Front-End Development to Data Analytics. I am always eager to explore and learn new technologies through various projects and experiences I have had, such as developing a production monitoring application to data processing projects. In addition to technical skills, my organizational experience has helped me develop communication, teamwork, responsibility, and time management skills, making me adaptable to various roles in the tech industry.",
        "education_title": "Education",
        "uni_name": "Universitas Darma Persada",
        "uni_major": "Information Systems",
        "uni_semester": "Semester 7",
        
        "projects_title": "My Projects",
        "proj3_title": "Android Application",
        "proj3_desc": "A mobile-based application developed specifically to run on the Android operating system, optimizing the mobile user interface.",
        "proj4_title": "Cisco Network Simulation",
        "proj4_desc": "Detailed simulation of computer network design and topology using Cisco Packet Tracer software.",
        "btn_view_project": "View Project",
        
        "skills_title": "My Skills",
        "tech_skills": "Technical Skills",
        "soft_skills": "Soft Skills",
        "skill_analytical": "Analytical Thinking",
        "skill_teamwork": "Teamwork",
        "skill_communication": "Communication",
        "skill_time": "Time Management",
        "skill_responsibility": "Responsibility",
        "skill_adaptability": "Adaptability",
        "skill_attention": "Attention to Detail",
        
        "exp_title": "Experience & Organization",
        "exp1_date": "June - August 2026",
        "exp1_role": "Web Developer Intern",
        "exp1_company": "PT Metinca Prima Industrial Works Jakarta",
        "exp1_desc1": "Developed a web-based production monitoring application using Laravel and MySQL.",
        "exp1_desc2": "Assisted in designing a monitoring system to facilitate production data tracking.",
        "exp2_date": "Past",
        "exp2_role": "Former Head of Equipment Division",
        "exp2_company": "UKM SOCCA UNSADA",
        "exp2_desc1": "Properly managed the organization's inventory.",
        "exp2_desc2": "Organized the process of borrowing and returning equipment.",
        "exp2_desc3": "Coordinated with the board regarding equipment needs.",
        
        "contact_title": "LET'S CONNECT",
        "contact_subtitle": "Have a question, opportunity, or project?",
        "contact_info_title": "Contact Information",
        "form_title": "Send a Message",
        "form_name": "Name",
        "form_email": "Email",
        "form_subject": "Subject",
        "form_message": "Message",
        "form_name_ph": "Your Name",
        "form_email_ph": "Your Email",
        "form_subject_ph": "Subject",
        "form_message_ph": "Your Message...",
        "btn_send": "Send Message",
        "footer_text": "© 2026 Ridho Fisabilillah. All rights reserved."
    },
    "id": {
        "nav_home": "Beranda",
        "nav_about": "Tentang Saya",
        "nav_portfolio": "Portofolio",
        "nav_skills": "Keahlian",
        "nav_experience": "Pengalaman",
        "nav_contact": "Kontak",
        
        "role": "Mahasiswa Sistem Informasi | Penggiat Teknologi",
        "sidebar_role": "Mahasiswa Sistem Informasi | Penggiat Teknologi",
        
        "home_greeting": "HALO, SAYA",
        "home_desc": "Mahasiswa semester 7 Sistem Informasi di Universitas Darma Persada. Seorang Penggiat Teknologi yang antusias mengeksplorasi berbagai bidang IT, seperti Pengembangan Web, Front-End, dan Analisis Data. Siap beradaptasi dan berkembang di industri teknologi.",
        "btn_portfolio": "Lihat Portofolio",
        "btn_cv": "Unduh CV",
        "what_i_do": "Apa Yang Saya Lakukan",
        "wd_web_desc": "Membangun aplikasi web responsif dan dinamis menggunakan teknologi modern seperti Laravel, PHP, dan Vanilla JavaScript.",
        "wd_data_desc": "Mengolah dan memvisualisasikan data untuk mendukung pengambilan keputusan menggunakan tools visualisasi data.",
        "wd_org_desc": "Berpengalaman dalam mengelola administrasi, manajemen waktu, serta berkolaborasi dalam tim secara efektif.",
        
        "featured_projects": "Proyek Unggulan",
        "proj1_title": "Sistem Monitoring Produksi",
        "proj1_desc": "Aplikasi berbasis web untuk membantu monitoring proses produksi antar cabang secara terpusat.",
        "proj2_title": "Dashboard Deteksi Fraud",
        "proj2_desc": "Dashboard visualisasi data interaktif untuk mendeteksi anomali pada dataset perusahaan.",
        "btn_all_projects": "Lihat Semua Proyek",
        
        "profile_title": "Profil",
        "profile_desc": "Mahasiswa semester 7 Sistem Informasi di Universitas Darma Persada. Saya adalah seorang Penggiat Teknologi yang memiliki ketertarikan luas di bidang IT, mulai dari Pengembangan Web, Front-End, hingga Analisis Data. Saya selalu bersemangat untuk mengeksplorasi hal-hal baru melalui berbagai project dan pengalaman yang saya jalani, seperti pengembangan aplikasi monitoring produksi hingga project pengolahan data. Selain kemampuan teknis, pengalaman organisasi juga membantu saya mengembangkan kemampuan komunikasi, kerja sama, tanggung jawab, dan manajemen waktu, menjadikan saya siap beradaptasi dalam berbagai peran di industri teknologi.",
        "education_title": "Pendidikan",
        "uni_name": "Universitas Darma Persada",
        "uni_major": "Sistem Informasi",
        "uni_semester": "Semester 7",
        
        "projects_title": "Proyek Saya",
        "proj3_title": "Aplikasi Android",
        "proj3_desc": "Aplikasi berbasis mobile yang dikembangkan khusus untuk berjalan di sistem operasi Android, mengoptimalkan antarmuka pengguna mobile.",
        "proj4_title": "Simulasi Jaringan Cisco",
        "proj4_desc": "Simulasi desain dan topologi jaringan komputer secara mendetail menggunakan perangkat lunak Cisco Packet Tracer.",
        "btn_view_project": "Lihat Proyek",
        
        "skills_title": "Keahlian Saya",
        "tech_skills": "Keahlian Teknis",
        "soft_skills": "Keahlian Non-Teknis",
        "skill_analytical": "Berpikir Analitis",
        "skill_teamwork": "Kerjasama Tim",
        "skill_communication": "Komunikasi",
        "skill_time": "Manajemen Waktu",
        "skill_responsibility": "Tanggung Jawab",
        "skill_adaptability": "Adaptabilitas",
        "skill_attention": "Perhatian terhadap Detail",
        
        "exp_title": "Pengalaman & Organisasi",
        "exp1_date": "Juni - Agustus 2026",
        "exp1_role": "Intern Web Developer",
        "exp1_company": "PT Metinca Prima Industrial Works Jakarta",
        "exp1_desc1": "Mengembangkan aplikasi web monitoring produksi menggunakan Laravel dan MySQL.",
        "exp1_desc2": "Membantu merancang sistem monitoring untuk mempermudah pemantauan data produksi.",
        "exp2_date": "Masa Lalu",
        "exp2_role": "Mantan Kepala Divisi Perlengkapan",
        "exp2_company": "UKM SOCCA UNSADA",
        "exp2_desc1": "Mengelola inventaris organisasi dengan baik.",
        "exp2_desc2": "Mengatur proses peminjaman dan pengembalian peralatan.",
        "exp2_desc3": "Berkoordinasi dengan pengurus terkait kebutuhan perlengkapan.",
        
        "contact_title": "MARI TERHUBUNG",
        "contact_subtitle": "Punya pertanyaan, peluang, atau proyek?",
        "contact_info_title": "Informasi Kontak",
        "form_title": "Kirim Pesan",
        "form_name": "Nama",
        "form_email": "Email",
        "form_subject": "Subjek",
        "form_message": "Pesan",
        "form_name_ph": "Nama Anda",
        "form_email_ph": "Email Anda",
        "form_subject_ph": "Subjek",
        "form_message_ph": "Pesan Anda...",
        "btn_send": "Kirim Pesan",
        "footer_text": "© 2026 Ridho Fisabilillah. Hak Cipta Dilindungi."
    }
};
